export interface CountryCode {
    [key: string]: string;
}

export const countryNames: CountryCode = {
    "TUR": "Turkey",
    "SRB": "Serbia",
    "ROU": "Romania",
    "UKR": "Ukraine",
    "MEX": "Mexico",
    "MWI": "Malawi",
    "ZAF": "South Africa",
    "SWZ": "Eswatini",
    "TZA": "Tanzania",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
    "ARG": "Argentina",
    "BOL": "Bolivia",
    "COL": "Colombia",
    "GUF": "French Guiana Franc",
    "GUY": "Guyana",
    "PRY": "Paraguay",
    "PER": "Peru",
    "SUR": "Suriname",
    "URY": "Uruguay",
    "VEN": "Venezuela",
    "CMR": "Cameroon",
    "GAB": "Gabon",
    "MNE": "Montenegro",
    "GRC": "Greece",
    "MKD": "North Macedonia",
    "UNK": "Unknown",
    "BEN": "Benin",
    "TCD": "Chad",
    "NER": "Niger",
    "SEN": "Senegal",
    "DJI": "Djibouti",
    "ETH": "Ethiopia",
    "KEN": "Kenya",
    "OMN": "Oman",
    "SAU": "Saudi Arabia",
    "BRN": "Brunei",
    "IDN": "Indonesia",
    "THA": "Thailand",
    "IRL": "Ireland",
    "DZA": "Algeria",
    "MRT": "Mauritania",
    "MAR": "Morocco",
    "GBR": "Great Britain and Northern Ireland",
    "BRA": "Brazil",
    "IND": "India",
    "BWA": "Botswana",
    "LSO": "Lesotho",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "IRQ": "Iraq",
    "TUN": "Tunisia",
    "LBY": "Libya",
    "ESH": "Western Sahara",
    "MLI": "Mali",
    "AGO": "Angola",
    "AIA": "Anguila",
    "ALB": "Albania",
    "AND": "Andorra",
    "ARE": "United Arab Emirates",
    "ARM": "Armenia",
    "ATG": "Antigua and Barbuda",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgaria",
    "BHR": "Bahrain",
    "BHS": "Bahamas, The",
    "BIH": "Bosnia and Herzegovina",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BMU": "Bermuda",
    "BRB": "Barbados",
    "BTN": "Bhutan",
    "CAN": "Canada",
    "CHE": "Switzerland",
    "CHL": "Chile",
    "CHN": "China",
    "CIV": "Cote d'Ivoire",
    "COD": "Congo, Dem. Rep.",
    "COG": "Congo, Rep.",
    "COM": "Comoros",
    "CPV": "Cape Verde",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CYM": "Cayman Islands",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DEU": "Germany",
    "DMA": "Dominica",
    "DNK": "Denmark",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ERI": "Eritrea",
    "ESP": "Spain",
    "EST": "Estonia",
    "FIN": "Finland",
    "FJI": "Fiji",
    "FLK": "Falkland Island",
    "FRA": "France",
    "FRO": "Faeroe Islands",
    "FSM": "Micronesia, Fed. Sts.",
    "GEO": "Georgia",
    "GGY": "Guernsey",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinea",
    "GLP": "Guadeloupe",
    "GMB": "Gambia, The",
    "GNB": "Guinea-Bissau",
    "GNQ": "Equatorial Guinea",
    "GRD": "Grenada",
    "GRL": "Greenland",
    "GTM": "Guatemala",
    "GUM": "Guam",
    "HKG": "Hong Kong, China",
    "HMD": "Heard Island and McDonald Islands",
    "HND": "Honduras",
    "HRV": "Croatia",
    "HTI": "Haiti",
    "HUN": "Hungary",
    "IMN": "Isle of Man",
    "IOT": "British Indian Ocean Ter.",
    "IRN": "Iran",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KGZ": "Kyrgyz Republic",
    "KHM": "Cambodia",
    "KIR": "Kiribati",
    "KNA": "St. Kitts and Nevis",
    "KOR": "Korea, Rep.",
    "KWT": "Kuwait",
    "LAO": "Lao PDR",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LCA": "St. Lucia",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "MAC": "Macao",
    "MAF": "Saint Martin (French part)",
    "MCO": "Monaco",
    "MDA": "Moldova",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MHL": "Marshall Islands",
    "MLT": "Malta",
    "MMR": "Myanmar",
    "MNG": "Mongolia",
    "MNP": "Northern Mariana Islands",
    "MSR": "Montserrat",
    "MTQ": "Martinique",
    "MUS": "Mauritius",
    "MYS": "Malaysia",
    "MYT": "Mayotte",
    "NCL": "New Caledonia",
    "NFK": "Norfolk Island",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niue",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "NPL": "Nepal",
    "NRU": "Nauru",
    "NZL": "New Zealand"
    // Add more country codes and names as needed
};