import type { Metadata } from "next";
import {Source_Sans_3} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";

const source_san_3 = Source_Sans_3({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        'min-h-screen antialiased',
        source_san_3.className
      )}>
        <Providers>
          <Navbar />
          <div className="h-full pt-12 mx-auto">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
